#
<<<<<<< HEAD
# TotalFreedomMod 2019.3.2 Configuration
=======
# TotalFreedomMod 5.0 Configuration
>>>>>>> devel
# by Madgeek1450 and Prozza
#

# Generic server information
server:
  # You should change this to your server's name
  name: TotalFreedom

  # The address your server is located at. Please do not include the port.
  address: play.totalfreedom.me

  # Shown at the server list - Please note that support for %mcversion% has been withdrawn
  motd: TotalFreedom &8- The Original All-Op Server!

  # Every word in the MOTD will be a different color unless prefixed by a color code
  colorful_motd: true

  # All players who show up as owner
  owners:
<<<<<<< HEAD
    - idiotpolice
    - GeminiTaze

  # All players who show up as executive
  executives:
    - Rodmous

  # All players who can manage the master builder list
  master_builder_management: []
=======
    - TheMinecraft
>>>>>>> devel

  # URL players should appeal for bans at
  ban_url: http://totalfreedom.boards.net/

  # URL players should appeal for permanent bans at
  permban_url: http://bit.ly/TF_PermBan

<<<<<<< HEAD
# Discord
discord:
  # If you do not have a token, make a bot account and get one at https://discordapp.com/developers/applications/me
  token: ''
  # The official Discord server's ID for this server
  server_id: ''
  # Channel to send /report messages to
  report_channel_id: ''
  # Do you want roles to sync with the server?
  role_sync: false
  # Super Admin role ID
  super_role_id: ''
  # Telnet Admin role ID
  telnet_role_id: ''
  # Senior Admin role ID
  senior_role_id: ''

=======
>>>>>>> devel
# Admin list
adminlist:

  # The amount of hours after which admins may be removed from the admin list
  clean_threshold_hours: 167

  # Give the default CONSOLE senior admin privileges.
  # Handy in development environments.
  console_is_senior: true

<<<<<<< HEAD
# CoreProtect
coreprotect:
  enabled: false
  host: 'localhost'
  port: '3306'
  username: ''
  password: ''
  database: 'coreprotect'

=======
>>>>>>> devel
# ForceIP configuration
forceip:
  enabled: false

  # The port players should use to connect to your server; only applies to forceip
  port: 25565

  # The kick message sent to players when logging in with the wrong hostname
  kickmsg: You have been kicked from the server - Please connect using %address%

<<<<<<< HEAD
# TotalFreedom Social Media Links, casing will be preserved
social_links:
  Forum: 'UNDER MAINTENANCE'
  Discord: 'https://discord.gg/q3A3Xrs'

=======
>>>>>>> devel

# Blocking certain events
allow:
  fire_place: false
  fire_spread: false
  fluid_spread: false
  lava_place: false
  lava_damage: false
  water_place: false
  tnt_minecarts: false
  explosions: false
<<<<<<< HEAD
  redstone: true
  fireworks: false
  frostwalker: false
  unsafe_enchantments: true
=======
>>>>>>> devel

# Blocked commands:
#
# How blocked commands work:
# All sections described below are delimited by colon characters.
# Make sure that you block a command by its main command name, not an alias
# as all aliases are blocked by default. Commands are case-insensitive.
#
# * The first section is a letter which indicates which rank may use this command
#   Valid ranks:
#   n - Nobody (Completely disabled)
#   c - Senior Admins (Console)
#   t - Telnet Admins (Console)
#   s - Super Admins (Any in-game admin)
#   o - Ops (Non-Ops won't be able to use it)
#
# * The second section is a letter which indicates what to do when a player executes that command.
#   Valid actions:
#   b - Block the command
#   a - Block the command and auto-eject that player (for ops and below)
#   u - Block the command and Return an "Unknown command" message (Used to hide commands)
#
# * The third section is the command to be blocked, prefixed with a slash
#
# * The fourth section is the message to send to the player when executing that command.
#   This should be ommited if unwanted. ChatColors are supported with the &-key. By default
#   -the starting ChatColor is set to gray. You can use the default 'That command is blocked.' message
#   by using a single underscore.
#
# Examples:
#   - 'n:b:/mail sendall:&4You can't send mails to everyone!'
#   - 's:a:/stop'
#   - 'n:b:/ban:_'
#
blocked_commands:
<<<<<<< HEAD
  # Disabled commands
  - 'n:b:/time:Server-side time changing is disabled. Please use /ptime to set your own personal time.'
  - 'n:b:/gamemode:Use /creative and /survival to set your gamemode.'
=======
    # Disabled commands
  - 'n:b:/time:Server-side time changing is disabled. Please use /ptime to set your own personal time.'
  - 'n:b:/gamemode:Use /creative and /survival to set your gamemode.'
  - 'n:b:/ban:_'
>>>>>>> devel
  - 'n:b:/pardon:_'
  - 'n:b:/ban-ip:_'
  - 'n:b:/pardon-ip:_'
  - 'n:b:/toggledownfall:_'
  - 'n:b:/effect:Please use /potion to set effects.'
  - 'n:b:/enderchest:_'
  - 'n:b:/spreadplayers:_'
  - 'n:b:/execute:_'
  - 'n:b:/blockdata:_'
  - 'n:b:/clearhistory:_'
  - 'n:b:/save-on:_'
  - 'n:b:/save-off:_'
  - 'n:b:/playsound:_'
  - 'n:b:/skinrestorer:_'
  - 'n:b:/packet:_'
  - 'n:b:/thaw:_'
  - 'n:b:/pp largeexplode:You may not use this particle! Please use another.'
  - 'n:b:/pp hugeexplosion:You may not use this particle! Please use another.'
  - 'n:b:/pp barrier:You may not use this particle! Please use another.'
  - 'n:b:/setjail:_'
<<<<<<< HEAD
  - 'n:b:/function:_'
  - 'n:b:/data:_'
  - 'n:b:/datapack:_'
  - 'n:b:/bossbar:_'
  - 'n:b://forceload:_'

  # Admin commands
=======
  - 'n:b:/tfbanlist:Use /banlist to see and wipe the ban list'
  - 'n:b:/tfipbanlist:Use /banlist to see and wipe the ban list'

  # Superadmin commands
>>>>>>> devel
  - 's:b:/save-all:_'
  - 's:b:/kick:_'
  - 's:b:/socialspy:_'
  - 's:b:/replaceitem:_'
  - 's:b:/kill:_'
  - 's:b://generate:_'
  - 's:b://:_'
  - 's:b:/superpickaxe:_'
  - 's:b:/brush:_'
  - 's:b:/size:_'
  - 's:b://mask:_'
  - 's:b:/mat:_'
  - 's:b://butcher:_'
  - 's:b:/scoreboard:_'
  - 's:b:/setspawn:_'
  - 's:b://snow:_'
  - 's:b:/tellraw:_'
  - 's:b:/forestgen:_'
  - 's:b:/setidletimeout:_'
  - 's:b:/mail sendall:_'
  - 's:b:/eco reset:_'
  - 's:b:/mask:_'
  - 's:b:/gmask:_'
  - 's:b:/lrbuild:_'
  - 's:b:/defaultgamemode:_'
  - 's:b:/reload:_'
  - 's:b:/title:_'
  - 's:b:/worldborder:_'
  - 's:b:/weather:_'
  - 's:b:/tpall:_'
  - 's:b:/setblock:_'
  - 's:b:/green:_'
  - 's:b:/gamerule:_'
  - 's:b:/togglejail:_'
  - 's:b:/fill:_'
  - 's:b:/flood:_'
<<<<<<< HEAD
  - 's:b:/team:_'

# Commands that should be blocked in certain circumstances
blocked:
  # Commands blocked from wildcard
  wildcard_commands:
    - wildcard
    - gtfo
    - doom
    - saconfig
  # Commands blocked while a player is muted
  muted_commands:
    - say
    - me
    - msg
    - tell
    - reply
    - mail
  # Blocked Chat Codes - Use &code,&code2,&code3 (No spaces)
  chatcodes: "&0,&k,&m,&n"

# Automatically wipe dropped objects
auto_wipe: false
=======

  # Superadmin commands - Auto-eject
  - 's:a:/stop:_'
  - 's:a:/restart:_'

# Automatically wipe dropped objects
auto_wipe: true
>>>>>>> devel

# Nuking prevention
nukemonitor:
  enabled: true
  count_break: 100
  count_place: 40
  range: 10.0

freecam_trigger_count: 10
explosive_radius: 4.0

# Show all attempted commands in the log, will result in duplicate log messages
preprocess_log: true

# Disable certain events
disable:
<<<<<<< HEAD
  night: false
  weather: false
=======
  night: true
  weather: true

>>>>>>> devel

# Enable misc. features
landmines_enabled: false
mp44_enabled: false
<<<<<<< HEAD
tossmob_enabled: true
=======
tossmob_enabled: false
>>>>>>> devel

# Moblimiter
moblimiter:
  enabled: true
  max: 50
  disable:
    dragon: true
    ghast: true
    slime: true
    giant: true

# Flatlands
flatlands:
  generate: true

  # Flatlands generation parameters - Uses CleanroomGenerator syntax - http://dev.bukkit.org/server-mods/cleanroomgenerator/
<<<<<<< HEAD
  generate_params: 16,stone,32,dirt,1,grass_block

# Admin-Only Mode
admin_only_mode: true

# Protected Areas - Protect areas so that only admins can directly modify blocks in those areas. WorldEdit and other such plugins might bypass this.
=======
  generate_params: 16,stone,32,dirt,1,grass

# Admin-Only Mode
admin_only_mode: false

# Protected Areas - Protect areas so that only superadmins can directly modify blocks in those areas. WorldEdit and other such plugins might bypass this.
>>>>>>> devel
protectarea:
  enabled: true
  auto_protect_spawnpoints: true
  auto_protect_radius: 25.0

# Host Sender Names - Names that indicate automated services or host-based consoles you want to block from using some commands.
# Make sure these are all lower-case.
host_sender_names:
  - rcon
  - remotebukkit
<<<<<<< HEAD

# Announcer
announcer:
  enabled: false
=======
  - console

# Announcer
announcer:
  enabled: true
>>>>>>> devel

  # Interval between announcements, in seconds.
  interval: 600

  # Prefix for all announcements
<<<<<<< HEAD
  prefix: '4&lIPD&c&lFreedom&3: '
=======
  prefix: '&5[&eTotalFreedom&5] &b'
>>>>>>> devel

  announcements:
    - 'Be sure to visit our forums at &6http://totalfreedom.boards.net/'
    - 'You can always review the server rules here: &6http://totalfreedom.me/'
    - 'If you are not OP, be sure to ask!'
    - 'Somebody breaking the rules? Report it! /report <user> <reason>'
    - 'Griefing is not allowed!'
    - 'Hacked clients are allowed!'
<<<<<<< HEAD
    - 'Interested in becoming admin? Type "/ai" for more information!'
=======
    - 'Interested in becoming admin? Do "/ai" for more information!'
>>>>>>> devel
    - 'You may view all online administrators via "/list -a"'
    - 'Save your buildings via WorldEdit! http://totalfreedom.me for more information!'
    - 'Famous players, such as Notch, are always fake! We are an offline/cracked server!'
    - 'You may contact TotalFreedom support on Twitter! https://tiny.re/tfsupport'
    - 'You may download TotalFreedomMod here: https://tiny.re/tfm+'
<<<<<<< HEAD
    - 'Catholic_Mario is the owner of TotalFreedom.'
    - 'MarkByron is the founder of TotalFreedom.'
    - 'Server lagging? Check the lag via "/tps"'
=======
    - 'MarkByron is the owner of TotalFreedom.'
    - 'Server lagging?  Check the lag via "/tps"'
>>>>>>> devel
    - 'You are allowed to record and stream videos on TotalFreedom.'
    - 'Player vs player while in creative or god mode is forbidden!'
    - 'Spawn killing is forbidden!'
    - 'Invisible potions are allowed!'
    - 'Serial griefing and trolling will result in a permanent ban!'
    - 'TotalFreedom does not accept any form of donations!'
    - 'Racism, nazism, and sexism are strictly forbidden!'
<<<<<<< HEAD
    - 'Join our Discord server! Link: https://discordapp.com/invite/XXjmAmV/'

# What to display in the admininfo command.
admininfo:
  - '&bHow to apply for admin on the IPDFreedom Server:'
  - ' &6- Do not ask for admin in game'
  - ' &2- Be helpful within the server'
  - ' &6- Report those breaking the rules'
  - ' &2- And apply on our forums at the link:'
  - '    &4CURRENTLY NOT AVAILABLE'

# What to display in the Master Builder info command.
masterbuilderinfo:
  - '&bHow to apply for Master Builder on the IPDFreedom Server:'
  - ' &6- Do not ask for Master Builder in game'
  - ' &2- Screenshot some of your previous builds (be ready to prove that the builds are yours)'
  - ' &6- Copy the template and create a thread on our forums'
  - ' &2- Template:'
  - '    &4CURRENTLY NOT AVAILABLE'
=======
    - 'Join our Mumble server! IP: 64.34.202.140:2862'
>>>>>>> devel

# Famous players - cannot be banned by username
famous_players:
  - honeydew
<<<<<<< HEAD
  - idiotpolice
=======
>>>>>>> devel
  - xephos
  - captainsparklez
  - truemu
  - kiershar
  - fvdisco
  - sethbling
  - notch
  - jeb_
  - gamechap
  - bertiechap
  - vechs
  - antvenom
  - chimneyswift
  - deadmau5
  - etho
  - ethoslab
  - skydoesminecraft
  - skythekidrs
  - tobyturner
  - xxslyfoxhoundxx
  - paulsoaresjr
  - sips_
  - deadlox
  - xxslyxx
  - jeromeasf
  - dinnerbone
  - grumm
  - grum
  - evilseph
  - cavemanfilms
  - herobrine
  - whiteboy7thst
  - stampylonghead
  - stampylongnose
  - dantdm
  - gizzy14gazza
  - furiousdestroyer

# IPs that can not be supered
noadmin_ips:
  - 167.114.97.16

# Pet Protect - Prevent tamed pets from being killed.
petprotect:
  enabled: true

# Logviewer
logs:
  url: ''
  secret: ''

# Mojang service checker
service_checker_url: http://status.mojang.com/check

# HTTPD server
httpd:
  enabled: true
<<<<<<< HEAD
  port: 2666
=======
  port: 28966
>>>>>>> devel
  public_folder: ./public_html

# Inactivity Auto-Kick (Requires Essentials)
autokick:
  enabled: true

  # Percentage of server player capacity used at which players will be automatically kicked for being inactive. Range: 0.0 - 1.0
  threshold: 0.9

  # Time, in seconds, after which a player should be kicked when inactive
  time: 120

# Players with access to the overlord command
overlord_ips:
  - 176.56.237.227
  - 192.184.86.138
  - 107.191.101.27
  - 178.62.117.94
  - 141.101.104.243
<<<<<<< HEAD
  - 192.168.1.114

# AMP Integration, used to restart server (optional, without it, have to start server manually after stop)
amp:
  enabled: false
  username: username
  password: password
  url: url
=======

>>>>>>> devel
