name: TotalFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
<<<<<<< HEAD
version: ${project.version}
description: Plugin for the Total Freedom server.
depend: [Aero]
softdepend: [BukkitTelnet, CoreProtect, Essentials, LibsDisguises, WorldEdit]
authors: [Madgeek1450, Prozza]
api-version: 1.13
=======
version: ${tfm.build.version}
description: Plugin for the Total Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
>>>>>>> devel
